apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-deploy
  labels:    
    env: dev    
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata: 
      name: store-deploy
      labels:
        tier: frontend
    spec: 
      containers: 
        - name: store-deploy
          image: calebespinoza/store-products:3.0
          ports:
          - containerPort: 80
