apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: jenkins-rs
  labels:
    app: web-server
    env: dev
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata: 
      name: jenkins
      labels:
        tier: frontend
    spec: 
      containers: 
        - name: jenkins
          image: jenkins/jenkins
          ports:
          - containerPort: 80
